import Head from 'next/head';
import styled from 'styled-components';

const Background = styled.div`
  width: 100vw;
  height: 100vw;
  position: absolute;
  top: 0;
  left: 0%;
  background: #022533;
`;

const Rect1 = styled.div`
  width: 90vw;
  height: 1.7vw;
  background: #812907;
  position: absolute;
  top: 4.3%;
  right: -51px;
  transform: rotate(22deg);
`;

const Rect2 = styled.div`
  width: 115vw;
  height: 1.7vw;
  background: #dd582f;
  position: absolute;
  top: 15.6%;
  right: -7%;
  transform: rotate(-26.7deg);
`;


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Background>
        <Rect1 />
        <Rect2 />
        </Background>
        

    </>
  )
}
