import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import telephone from '../public/images/telephone.png';
import handset from '../public/images/handset.png';
import paper1 from '../public/images/paper1.png';
import paper2 from '../public/images/paper2.png';

const Background = styled.div`
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0%;
  background: #022533;
`;

const LineOne = styled.div`
  width: 90vw;
  height: 1.7vw;
  background: #812907;
  position: absolute;
  top: 4%;
  right: -150px;
  transform: rotate(22deg);
`;

const PhoneContainer = styled.div`
  height: 25vh;
  width: 25vw;
  position: absolute;
  top: 3%;
  left: 8%;
  transform: rotate(26.7deg);
`;

const LineTwo = styled.div`
  width: 170vw;
  height: 1.7vw;
  background: #dd582f;
  position: absolute;
  top: 15%;
  left: -250px;
  transform: rotate(-26.7deg);
`;

const PaperOneContainer = styled.div`
  height: 27vh;
  width: 27vw;
  position: absolute;
  top: 23%;
  right: 11%;
  transform: rotate(16deg);
`;

const TextContainer = styled.div`
  width: 85.9vw;
  height: 8vw;
  background: #F4BD40;
  position: absolute;
  top: 46%;
  right: -2%; 
  transform: rotate(9.71deg);
  display: flex;
  justify-content: center;
  align-items: center;  
  padding: 15px;

  p {
    padding: 10px;
    font-size: 2vw;
  }
`;

const Handset = styled.div`
  height: 32vh;
  width: 32vw;
  position: absolute;
  top: 53%;
  right: 22%;
  transform: rotate(300deg);
`;

const PaperTwoContainer = styled.div`
  height: 22vh;
  width: 22vw;
  position: absolute;
  top: 60%;
  left: 5%;
  transform: rotate(270deg);
`;

const LineThree = styled.div`
  width: 160vw;
  height: 1.7vw;
  background: #812907;
  position: absolute;
  top: 88%;
  left: -150px;
  transform: rotate(-4deg);
`;


export default function Home() {
  return (
    <>
      <Head>
        <title>SuzeeThunder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Background>
          <LineOne/>
          <PhoneContainer>
            <Image src={telephone} />
          </PhoneContainer>
          <LineTwo/>
          <PaperOneContainer>
            <Image src={paper1} />
          </PaperOneContainer>
          <TextContainer>
            <p>
            In the '80s, Dan Granata ran with the best of them - phone phreakers, social engineers, and the most notorious computer hackers of the era. Then he got a job at designory. 
            </p>  
          </TextContainer>
          <PaperTwoContainer>
            <Image src={paper2} />
          </PaperTwoContainer>
          <Handset>
            <Image src={handset} />
          </Handset>
          <LineThree />
        </Background>
        

    </>
  )
}
